### ISSUE TITLE
🏎 Minor feature request: add sliding scale for EQ-5D-5L questionnaire

### ISSUE THREAD

**Issue by karansoin** [CS342/2024-PICS#25]
### Problem

Sliding scale needed for a question is not currently there

### Solution

Figure out a way to make a custom slider to answer the 0 to 100 scale question

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
Hi @karansoin, 

Our ResearchKitOnFHIR package supports sliders in questionnaires. While this option is not present in the Phoenix survey builder yet, you can change any numerical question into a slider by manually editing the JSON. See the example below:

![image](https://github.com/CS342/2024-PICS/assets/1212163/08c3f472-6e1a-4728-bc47-3973e92f5a52)

Let us know if you have questions!

cc: @PSchmiedmayer @Supereg @philippzagar
